// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/ErrorMessage/403.vue')['default']
    404: typeof import('./src/components/ErrorMessage/404.vue')['default']
    500: typeof import('./src/components/ErrorMessage/500.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    LockScreen: typeof import('./src/components/LockScreen/src/LockScreen.vue')['default']
    Message: typeof import('./src/components/Message/src/Message.vue')['default']
    MessageBox: typeof import('./src/components/MessageBox/src/MessageBox.vue')['default']
    ModelSelect: typeof import('./src/components/ModelSelect/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RegionSelect: typeof import('./src/components/regionSelect/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    SwitchDark: typeof import('./src/components/SwitchDark/index.vue')['default']
    UploadFile: typeof import('./src/components/UploadFile/index.vue')['default']
    WangEditor: typeof import('./src/components/WangEditor/index.vue')['default']
    Webpage: typeof import('./src/components/Webpage/index.vue')['default']
  }
}

export { }
